window.mountCoachMonthly=function(container,{client,account,studentId,valid,back}){
 if(!['trainer','admin'].includes(account.role))return;
 const M=window.CoachMonthly,esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const button=(text,action,extra='')=>`<button type="button" class="btn light" data-m="${action}" ${extra}>${text}</button>`;
 const input=(key,label,value='',type='text')=>`<label style="display:block;min-width:0">${label}<input class="input" style="font-size:16px" name="${key}" type="${type}" value="${esc(value)}"></label>`;
 const area=(key,label,value='')=>`<label>${label}<textarea name="${key}" rows="3" style="font-size:16px">${esc(value)}</textarea></label>`;
 const exercise=()=>({name:'',sets:3,reps:'8-12',rest_seconds:90,target_weight:null,target_rir:null,notes:'',previous_exercise_id:null,change_reason:''});
 let data,draft=null,payload=null,busy=false,ticket=0,editMonth=null;
 const live=t=>()=>valid()&&t===ticket;
 const message=(text)=>{const e=container.querySelector('[role="status"]');if(e)e.textContent=text;};
 function frame(html){container.innerHTML=button('Voltar','back')+'<div role="status" aria-live="polite" class="card"></div>'+html;compactExercises();}
 function compactExercises(){
  container.querySelectorAll('[data-workout]').forEach(workout=>{
   workout.querySelectorAll(':scope > div').forEach((fields,index)=>{
    const details=document.createElement('details'),summary=document.createElement('summary');
    details.className='monthly-exercise';details.style.cssText='border-top:1px solid #edf1f5;';
    summary.style.cssText='padding:18px 0;cursor:pointer;list-style:none;display:flex;align-items:center;gap:12px;';
    const label=document.createElement('span'),name=document.createElement('strong'),prescription=document.createElement('span'),arrow=document.createElement('span');
    label.style.cssText='flex:1;min-width:0;overflow-wrap:anywhere';name.style.display='block';prescription.className='muted';prescription.style.cssText='display:block;margin-top:5px';arrow.textContent='›';arrow.setAttribute('aria-hidden','true');arrow.style.cssText='font-size:26px;color:#20ad75';
    const update=()=>{name.textContent=fields.querySelector('[name$="_name"]').value||`Exercício ${index+1}`;prescription.textContent=`${fields.querySelector('[name$="_sets"]').value||'—'} séries × ${fields.querySelector('[name$="_reps"]').value||'—'} reps`;};
    update();fields.addEventListener('input',update);label.append(name,prescription);summary.append(label,arrow);fields.before(details);details.append(summary,fields);fields.style.cssText='padding-bottom:16px;';
    details.addEventListener('toggle',()=>{arrow.textContent=details.open?'⌄':'›';});
   });
  });
 }
 async function load(){const t=++ticket;frame('<p>A carregar planos mensais…</p>');try{data=await M.read(client,account,studentId);if(!live(t)())return;list();}catch(e){if(live(t)()){frame(button('Tentar novamente','reload'));message(e.message);}}}
 function list(){draft=null;payload=null;editMonth=null;const c=data.context[0]||{};frame('<h2>Planos mensais</h2><p class="muted">Os rascunhos são privados. Revê os exercícios antes de aprovar. A publicação ocorre a partir do primeiro dia do mês; até lá, o aluno mantém o plano atual.</p>'+button('Gerar rascunho para o próximo mês','generate')+button('Criar do zero','new')+data.drafts.map(d=>`<div class="card"><h3>${esc(d.payload.name)}</h3><p>${esc(d.month.slice(0,7))} · ${{draft:'Por rever',approved:'Aprovado · aguarda início do mês',active:'Ativo',archived:'Arquivado'}[d.status]}</p><p class="muted">${d.source==='automatic'?'Gerado automaticamente':'Criado pelo treinador'}${d.generated_at?' · '+esc(new Date(d.generated_at).toLocaleString('pt-PT')):''}</p>${button(d.status==='draft'?'Rever / Editar':'Consultar','open',`data-id="${d.id}"`)}</div>`).join('')+data.jobs.filter(j=>j.state!=='done').map(j=>`<div class="card notice">${esc(j.month.slice(0,7))}: ${j.state==='running'?'Geração em curso. Volta a carregar dentro de alguns minutos.':'Geração falhou. Confirma os dados abaixo. Há até três tentativas, separadas por pelo menos dez minutos; podes sempre criar o plano manualmente.'}</div>`).join('')+button('Atualizar lista','reload')+`<form data-monthly="context" class="card"><h3>Dados para o próximo plano</h3>${input('objective','Objetivo',c.objective)}${input('experience','Experiência',c.experience)}${input('days_per_week','Dias por semana (1–7)',c.days_per_week,'number')}${area('limitations','Limitações / lesões (ou «Sem limitações conhecidas»)',c.limitations)}${area('feedback','Feedback / check-ins e preferências disponíveis',c.feedback)}<button class="btn green">Guardar dados</button></form>`);}
 function edit(){const readonly=draft&&draft.status!=='draft';frame(`<h2>${readonly?'Consultar plano':'Rever plano mensal'}</h2><form data-monthly="plan"><fieldset style="border:0;padding:0;min-width:0" ${readonly?'disabled':''}>${input('month','Mês',(editMonth||draft?.month||M.nextMonth()).slice(0,7),'month')}<div class="card">${input('name','Nome do plano',payload.name)}${input('objective','Objetivo',payload.objective)}</div>${payload.rationale?`<div class="card notice"><b>Notas internas para revisão</b><p style="white-space:pre-wrap;overflow-wrap:anywhere">${esc(payload.rationale)}</p></div>`:''}${payload.workouts.map((w,i)=>`<div class="card" data-workout="${i}">${input(`w${i}_name`,'Nome do treino',w.name)}${w.exercises.map((e,j)=>`<div style="border-top:1px solid #edf1f5;padding-top:12px">${input(`e${i}_${j}_name`,'Exercício',e.name)}${input(`e${i}_${j}_sets`,'Séries',e.sets,'number')}${input(`e${i}_${j}_reps`,'Repetições (ex.: 8-12)',e.reps)}${input(`e${i}_${j}_target_weight`,'Carga alvo (kg)',e.target_weight)}${input(`e${i}_${j}_target_rir`,'RIR alvo',e.target_rir)}${input(`e${i}_${j}_rest_seconds`,'Descanso (segundos)',e.rest_seconds)}${area(`e${i}_${j}_notes`,'Notas para o aluno',e.notes)}${e.change_reason?`<p class="muted">Revisão: ${esc(e.change_reason)}</p>`:''}${button('Remover exercício','removeExercise',`data-w="${i}" data-e="${j}"`)}</div>`).join('')}${button('Adicionar exercício','addExercise',`data-w="${i}"`)}${button('Remover treino','removeWorkout',`data-w="${i}"`)}</div>`).join('')}${button('Adicionar treino','addWorkout')}<button class="btn green" type="submit">Guardar rascunho</button></fieldset></form>${!readonly&&draft?button('Aprovar versão guardada','approve')+button('Substituir por plano do zero','reset'):''}`);}
 function collect(){const f=container.querySelector('[data-monthly="plan"]');const v=Object.fromEntries(new FormData(f));payload.name=v.name;payload.objective=v.objective;for(const [i,w]of payload.workouts.entries()){w.name=v[`w${i}_name`];for(const [j,e]of w.exercises.entries())for(const key of ['name','sets','reps','target_weight','target_rir','rest_seconds','notes']){const value=v[`e${i}_${j}_${key}`];e[key]=['sets','target_weight','target_rir','rest_seconds'].includes(key)?value.trim()===''?null:Number(value.replace(',','.')):value;}}editMonth=v.month+'-01';return editMonth;}
 function fresh(){payload={name:'Plano de '+M.nextMonth().slice(0,7),objective:data.context[0]?.objective||'',rationale:'',workouts:[{name:'Treino A',exercises:[exercise()]}]};edit();}
 async function act(fn){if(busy)return;busy=true;const t=ticket;container.querySelectorAll('button').forEach(b=>b.disabled=true);message('A guardar…');try{await fn(live(t));}catch(e){if(live(t)())message(e.message);}finally{busy=false;if(live(t)())container.querySelectorAll('button').forEach(b=>b.disabled=false);}}
 container.addEventListener('click',event=>{const b=event.target.closest('[data-m]');if(!b||!valid()||busy)return;const a=b.dataset.m;
  if(a==='back'){++ticket;return back();}if(a==='reload')return load();
  if(a==='new'){draft=null;editMonth=null;return fresh();}if(a==='reset')return fresh();
  if(a==='open'){draft=data.drafts.find(d=>d.id===b.dataset.id);editMonth=draft.month;payload=structuredClone(draft.payload);return edit();}
  if(a==='generate')return act(async current=>{const r=await M.generate(client,account,studentId,current);if(current()){await load();message(r.message);}});
  if(a==='approve')return act(async current=>{const month=collect();if(month!==draft.month||JSON.stringify(payload)!==JSON.stringify(draft.payload))throw new Error('Guarda as alterações antes de aprovar.');await M.approve(client,account,studentId,draft,current);if(current())await load();});
  if(['addWorkout','removeWorkout','addExercise','removeExercise'].includes(a)){collect();const i=Number(b.dataset.w),j=Number(b.dataset.e);if(a==='addWorkout'&&payload.workouts.length<7)payload.workouts.push({name:'Novo treino',exercises:[exercise()]});if(a==='removeWorkout')payload.workouts.splice(i,1);if(a==='addExercise'&&payload.workouts[i].exercises.length<30)payload.workouts[i].exercises.push(exercise());if(a==='removeExercise')payload.workouts[i].exercises.splice(j,1);edit();}
 });
 container.addEventListener('submit',event=>{const f=event.target;if(!f.dataset.monthly)return;event.preventDefault();if(!valid())return;act(async current=>{
  if(f.dataset.monthly==='context'){await M.context(client,account,studentId,Object.fromEntries(new FormData(f)),current);if(current()){await load();message('Dados guardados.');}}
  else{const month=collect();if(draft&&month!==draft.month)throw new Error('Para outro mês, cria um novo plano.');const saved=await M.save(client,account,studentId,month,payload,draft?.revision||0,current);if(current()){draft=saved;payload=structuredClone(saved.payload);edit();message('Rascunho guardado. Revê e aprova quando estiver pronto.');}}
 });});
 load();
};
