const {test}=require('node:test'),assert=require('node:assert/strict');
const {webcrypto}=require('node:crypto');
const W=require('../workouts.js');
const {fixture,trainer,maria,other}=require('./workout-fixture.cjs');
const pv={name:'Plano Maria',objective:'Força',start_date:'2026-01-01',end_date:'2027-01-01',active:true};
const ev={name:'Agachamento',position:'1',sets:'2',reps:'8–12',target_weight:'40,5',target_rir:'2',rest_seconds:'90',notes:'Controlar a descida'};
async function prepared(){const f=fixture(),c=f.client;await W.createPlan(c,trainer,maria.id,pv,'p');await W.createWorkout(c,trainer,maria.id,'p',{name:'Treino A',position:'1'},'w');await W.createExercise(c,trainer,maria.id,'w',ev,'e');return f;}
async function running(){const f=await prepared();f.actor=maria;await W.start(f.client,maria,maria.id,'w','s','2026-09-19');return f;}
const lv={weight:'42,5',reps:'10',rir:'1,5',notes:'Boa execução'};
test('trainer creates plan, workout and exercise using confirmed columns',async()=>{const f=await prepared();assert.equal(f.tables.workout_plans[0].trainer_id,trainer.id);assert.equal(f.tables.exercises[0].target_weight,40.5);assert.equal(f.tables.workouts[0].plan_id,'p');assert.equal((await W.planDetail(f.client,trainer,maria.id,'p')).workouts.length,1);});
test('inactive association blocks creation and state change',async()=>{const f=await prepared();f.tables.trainer_students[0].active=false;await assert.rejects(W.createWorkout(f.client,trainer,maria.id,'p',{name:'B',position:2},'x'));await assert.rejects(W.setActive(f.client,trainer,maria.id,'p',false));});
test('student cannot create plan or view another student',async()=>{const f=await prepared();f.actor=maria;await assert.rejects(W.createPlan(f.client,maria,maria.id,pv,'x'));await assert.rejects(W.plans(f.client,maria,other.id));assert.equal((await W.plans(f.client,maria,maria.id)).length,1);});
test('forged workout parent is rejected before creating exercise',async()=>{const f=await prepared();await assert.rejects(W.createExercise(f.client,trainer,other.id,'w',ev,'x'));assert.equal(f.tables.exercises.length,1);});
test('dates and required names validated',()=>{assert.throws(()=>W.planValues({...pv,name:' '}));assert.throws(()=>W.planValues({...pv,end_date:'2025-01-01'}));assert.throws(()=>W.planValues({...pv,start_date:'2026-02-30'}));assert.equal(W.planValues({...pv,end_date:''}).end_date,null);});
for(const key of ['position','sets','target_weight','target_rir','rest_seconds'])test(`exercise rejects negative ${key}`,()=>assert.throws(()=>W.exerciseValues({...ev,[key]:'-1'})));
test('integer series/reps, finite numbers and ranges validated',()=>{for(const v of ['0','2,5','101'])assert.throws(()=>W.exerciseValues({...ev,sets:v}));for(const v of ['-1','12-8','abc'])assert.throws(()=>W.exerciseValues({...ev,reps:v}));for(const v of ['Infinity','1e3','1,2.3'])assert.throws(()=>W.logValues({...lv,weight:v}));assert.throws(()=>W.logValues({...lv,reps:'2,5'}));assert.equal(W.logValues({...lv,weight:'0',rir:''}).weight,0);});
test('start persists and resumes same unfinished session after reload',async()=>{const f=await running();const s=await W.start(f.client,maria,maria.id,'w','different','2026-09-19');assert.equal(s.id,'s');assert.equal(f.tables.workout_sessions.length,1);assert.equal((await W.session(f.client,maria,maria.id,'s')).session.finished_at,null);});
test('inactive/out of date/empty workouts cannot start',async()=>{const f=await prepared();f.actor=maria;await assert.rejects(W.start(f.client,maria,maria.id,'w','s','2028-01-01'));f.tables.workout_plans[0].active=false;await assert.rejects(W.start(f.client,maria,maria.id,'w','s','2026-09-19'));f.tables.workout_plans[0].active=true;f.tables.exercises=[];await assert.rejects(W.start(f.client,maria,maria.id,'w','s','2026-09-19'));});
test('set logs persist and a repeated save never overwrites',async()=>{const f=await running();const id=await W.logId('s','e',1,webcrypto);await W.saveSet(f.client,maria,maria.id,'s','e',1,lv,id);const again=await W.saveSet(f.client,maria,maria.id,'s','e',1,{...lv,weight:99},id);assert.equal(again.recovered,true);assert.equal(f.tables.set_logs.length,1);assert.equal((await W.session(f.client,maria,maria.id,'s')).logs[0].weight,42.5);});
test('same prescribed set has stable UUID across reloads/tabs',async()=>{assert.equal(await W.logId('s','e',1,webcrypto),await W.logId('s','e',1,webcrypto));assert.notEqual(await W.logId('s','e',1,webcrypto),await W.logId('s','e',2,webcrypto));});
test('foreign exercise and invalid series are blocked',async()=>{const f=await running();for(const [e,n]of [['foreign',1],['e',0],['e',3]])await assert.rejects(W.saveSet(f.client,maria,maria.id,'s',e,n,lv,'x'));assert.equal(f.tables.set_logs.length,0);});
test('trainer cannot write student logs or finish sessions',async()=>{const f=await running();f.actor=trainer;await assert.rejects(W.saveSet(f.client,trainer,maria.id,'s','e',1,lv,'x'));await assert.rejects(W.finish(f.client,trainer,maria.id,'s',''));});
test('unfinished sets block completion, all saved sets allow completion and history',async()=>{const f=await running();await assert.rejects(W.finish(f.client,maria,maria.id,'s',''));for(let n=1;n<=2;n++)await W.saveSet(f.client,maria,maria.id,'s','e',n,lv,'l'+n);await W.finish(f.client,maria,maria.id,'s','Concluído');const h=await W.history(f.client,maria,maria.id);assert.ok(h.sessions[0].finished_at);assert.equal(h.sessions[0].notes,'Concluído');assert.equal(h.logs.length,2);await assert.rejects(W.saveSet(f.client,maria,maria.id,'s','e',1,lv,'another'));});
test('RLS denial never turns into success or fallback write',async()=>{const f=await running();f.deny='set_logs';await assert.rejects(W.saveSet(f.client,maria,maria.id,'s','e',1,lv,'l'),{code:'42501'});assert.equal(f.tables.set_logs.length,0);});
test('lost insert response is safely retried',async()=>{const f=await running();f.lose='set_logs';await assert.rejects(W.saveSet(f.client,maria,maria.id,'s','e',1,lv,'l'));assert.equal((await W.saveSet(f.client,maria,maria.id,'s','e',1,lv,'l')).recovered,true);assert.equal(f.tables.set_logs.length,1);});
test('navigation/session change prevents a write after async checks',async()=>{const f=await running();await assert.rejects(W.saveSet(f.client,maria,maria.id,'s','e',1,lv,'l',()=>false));assert.equal(f.tables.set_logs.length,0);});
test('PR is strictly higher weight for the same exercise and excludes unfinished sessions',()=>{
 const history={sessions:[{id:'a',started_at:'2026-01-01',finished_at:'yes'},{id:'b',started_at:'2026-01-02',finished_at:'yes'},{id:'c',started_at:'2026-01-03',finished_at:null}],logs:[{id:'1',session_id:'a',exercise_id:'e',set_number:1,weight:10,reps:8,completed:true},{id:'2',session_id:'b',exercise_id:'e',set_number:1,weight:12,reps:6,completed:true},{id:'3',session_id:'b',exercise_id:'e',set_number:2,weight:12,reps:8,completed:true},{id:'4',session_id:'c',exercise_id:'e',set_number:1,weight:99,completed:true}]};
 const p=W.progress(history,'e');assert.equal(p.best,12);assert.equal(p.last.id,'3');assert.deepEqual(p.logs.map(l=>l.pr),[false,true,false]);assert.equal(W.progress(history,'other').last,null);
});
